name: Bash CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  services:
    # mysql-service Label used to access the service container
    mysql-service:
      # Docker Hub image (also with version)
      image: mysql:5.7
      env:
        ## Accessing to Github secrets, where you can store your configuration
        MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        MYSQL_DATABASE: db_test
      ## map the "external" 33306 port with the "internal" 3306
      ports:
        - 33306:3306
      # Set health checks to wait until mysql database has started (it takes some seconds to start)
      options: >-
        --health-cmd="mysqladmin ping"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: list scripts to be tested
      run: ls ./*.sh

    - name: Check for basic execution
      run: ls ./*.sh | xargs bash

    - name: Unit testing with bash_unit
      run: tests/bash_unit tests/test_*
